#include "Declarations.h"



void print_logo(unsigned __int8 size)
{
	const char S_logo[76][78]	=	
	{
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMWN0xOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMN0d:'. cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMNOl,.     cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMN0l'         cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMXx;.           :NMMMMMMMMMMMMWNXK0OOOO0KXNWMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMWKo'              :NMMMMMMMWXOdc;''''''''''',;lx0NMMMMMMMMMMMM",
	"MMMMMMMMMMMXo.                :NMMMMWKd:'.':oxO0KXXXXK0kdl;'.'ckXWMMMMMMMM",
	"MMMMMMMMMNk,                  cNMMNO:..;d0NWMMMMMMMMMMMMMMWXOo,.'oKWMMMMMM",
	"MMMMMMMMKc.                   :NWO:.'o0WMMMMMMNXK0000KNWMMMMMMNO:..lKMMMMM",
	"MMMMMMWO,                     :0o..oKWMMMMNOd:,'''''''';cxKWMMMMWO:.'kWMMM",
	"MMMMMWx.                      ',.,OWMMMMKd,.':ok0KKKKOxl;..:kNMMMMNd..oNMM",
	"MMMMWx.                         ;KMMMMNd'.;kXWMMMMMMMMMMWKd'.;OWMMMWk..oNM",
	"MMMWk.                         ,0MMMMXc.'kNMMMMMMMMMMMMMMMMXo..dWMMMWx..kM",
	"MMMK,                         .dWMMMNl ,0MMMMMMMMMMMMMMMMMMMWx..xWMMMXc :M",
	"MMNl                          ,KMMMMk..xWMMMMMMMMNO0WMMMMMMMMNl ;KMMMMx..M",
	"MM0'                          :XMMMWo ,KMMMMMMMMMk.;KMMMMMMMMMk..OMMMMO..M",
	"MWo                           :XMMMWo ,KMMMMMMMMK;  oWMMMMMMMMk..OMMMMO..M",
	"MX:                           ,KMMMMk..kMMMMMMMNl   .kMMMMMMMNc ;KMMMMx..M",
	"MK,                           .xWMMMX: ;KMMMMMWk.    ;XMMMMMNo..kWMMMNc :M",
	"M0'                            ,0MMMMK;.;0WMMMK,     .oWMMWKc..kWMMMWx..kM",
	"M0'                             ;KMMMMXl..l0WNl       .ONOl..c0WMMMWk..oNM",
	"M0,                           .'.,OWMMMWOc..,;.        .'.'l0WMMMMNx..oNMM",
	"MX;                           :0l..oXMMMMWXx;           'kXWMMMMW0:.'xNMMM",
	"MNc                           :NWO;.'oKWMMMNc           'OMMMMNOc..lKMMMMM",
	"MWo                           :NMMNk:..:x0Nx.            :XNOo,.'l0WMMMMMM",
	"MMk.                          :NMMMMW0d;..'.              ''.'cxXWMMMMMMMM",
	"MMK,                          :NMMMMMMMWXd. ....      ...  :OXWMMMMMMMMMMM",
	"MMNl                          :NMMMMMMMMWd..dXK0OkkkOO0Kk' cNMMMMMMMMMMMMM",
	"MMMk.                         :NMMMMMMMMO' cNMMMMMMMMMMMWd..xWMMMMMMMMMMMM",
	"MMMX:                         :NMMMMMMMX: ,0MMMMMMMMMMMMMX: ,0MMMMMMMMMMMM",
	"MMMWx.                        :NMMMMMMWd..xWMMMMMMMMMMMMMMO' cNMMMMMMMMMMM",
	"MMMMXc                        :XMMMMMMO. cNMMMMMMMMMMMMMMMWo..xWMMMMMMMMMM",
	"MNNMMO'                       :NMMMMMX: ,0MMMMMMMMMMMMMMMMMX: ,KMMMMMMMMMM",
	"M0xNMWd.                      :XMMMMWo..xWMMMMMMMMMMMMMMMMMMO. lNMMMMMMMMM",
	"Mk:kMMNc                      :XMMMMO. lNMMMMMMMMMMMMMMMMMMMWo..kWMMMMMMMM",
	"Mk.cNMMK:                     :NMMMK; ;KMMMMMMMMMMMMMMMMMMMMMK; ;KMMMMMMMM",
	"Mk..kMMM0;                    :NMMNo .kWMMMMMMMMMMMMMMMMMMMMMMk. lNMMMMMMM",
	"Mk. cNMMM0,                   :XMWk. oNMMMMMMMMMMMMMMMMMMMMMMMNo .kMMMMMMM",
	"Mk. .kMMMMK;                  :XMK; ;KMMMMMMMMMMMMMMMMMMMMMMMMMK; ;KMMMMMM",
	"Mk.  :XMMMMXc                 :XNl .kMMMMMMMMMMMMMMMMMMMMMMMMMMWk. oWMMMMM",
	"Mk.  .dWMMMMNd.               :Xk. oNMMMMMMMMMMMMMMMMMMMMMMMMMMMNl .OMMMMM",
	"Mk.   '0MMMMMWO,              :k, :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK, :XMMMM",
	"Mk.    :XMMMMMMXl.            ,; .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx..oWMMM",
	"Mk.    .oNMMMMMMWO;             .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl .OMMM",
	"Mk.     .xWMMMMMMMNx,           :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0, :XMM",
	"Mk.      .kWMMMMMMMMXd'        'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx..dWM",
	"Mk.       'OWMMMMMMMMMXx,      .clllllllllooooooooooooooooooooooooooc. .lM",
	"Mk.        'OWMMMMMMMMMMNk:.                                             M",
	"Mk.         .xWMMMMMMMMMMMWKo,.                                          M",
	"Mk.          .oNMMMMMMMMMMMMMNOl,.                                       M",
	"Mk.            :0WMMMMMMMMMMMMMMNOo;.                                    M",
	"Mk.             .dNMMMMMMMMMMMMMMMMWKxc'.                                M",
	"Mk.               ,kNMMMMMMMMMMMMMMMMMMN0xc,.                            M",
	"Mk.                .;kNMMMMMMMMMMMMMMMMMMMMWKkdc,..                      M",
	"MO.                  .:OWMMMMMMMMMMMMMMMMMMMMMMMWX0koc;'..               M",
	"MN0kkkkkkkkkkkkkkOkkkkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxdolc:;;,,,,,:M",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMNP           'oKWMWo           .cKM0             DDD  .WMMMMMMXDl   lWMM",
	"M0   .lcloll:.   'OWWo    :x00d.   oW0     DDDDDDDDDKM   .:kNMMMNDl   lWMM",
	"M:   cNMMMMMWK:   ,KMO,    'cc,   .xWN     DDDDDDDDDDM     w;xNMXDl   lWMM",
	"M,   oWMMMMMMMx.  .OW0         ..:kNMK        DDDDDDDl   b    xO;Dl   lWMM",
	"Mc   .xXWMMWWNo.  :XWo    OOO000XWMMM0     DDDDDDDDKMx   ox:.   .Dl   lWMM",
	"MXc.   .;::;,;  ;c0MWo    XMMMMMMMMMM0     DDDDDDDDKMx   D0W0c.       lWMM",
	"MMNOc.         ;NWMMWo    KMMMMMMMMMM0            DDDD   D0MMW0llb    lWMM",
	"MMMMWX0xdoddxOXWMMMMMKxddONMMMMMMMMMMNkoooooooooooodKMKxookNMMMMWKDDDD0WMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMWWWMMWWWWWWWWWWWWMMWWWWWWWWWWWWMMMM",
	"MMMMMMMN''NMMMMMMMMMMMMMMMK'''OMMMMMMW''''KW''''''''''DDDDD''''''''''dNMMM",
	"MMMMMMN    0XMMMMMMMMMMMMMk   DDMMMMMM    Ol   .......DDOKl          :XMMM",
	"MMMMMX       XMMMMMMMMMMMMk   DDMMMMMWMMMM0l   DDDDDDOO0NXl   DDDDDDD0WMMM",
	"MMMMK         KMMMMMMMMMMMk   DDMMMMMW    Dl   DDDDDDDDMMNl   '''''''oNMMM",
	"MMW0   ,OOO    0MMMWOoooxKk   DDMMMMMW    Dl          MMMKl   .......cXMMM",
	"MWO             0WMW0xxxkXk   DDWXKXNW    Dl   DDDDDDDMMMKl   DDDDDDD0WMMM",
	"Mk    OWMMWWO    OWMMMMMMMk   DDDDDDoN    Dl   DNMMMMMMMMKl   '''''''cXMMM",
	"M    0MMMMMMW0    KMMMMMMM0       DDdN    Dl   DWMMMMMMMMXl          lXMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
	};

	const char M_logo[102][98] 	= 
	{
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKxxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc,. .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo;.     .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMXkl'         .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMNOl'            .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMWXd;.              .OMMMMMMMMMMMMMMMMMMMMMMWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMW0l.                 .OMMMMMMMMMMMMMMWNKkdoc:;;,,,,;:cldk0XWMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMW0c.                   .OMMMMMMMMMMWXko;'.  ...,,;;;,,'..  ..,cx0NMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMW0c.                     .OMMMMMMMWKd;.  .;ldk0XNWWWWWWWNXKOxo:'. .,lONMMMMMMMMMMMM",
	"MMMMMMMMMMMMMXo.                       .OMMMMMNk:. .,lOXWMMMMMMMMMMMMMMMMMMMWN0d:. .,dKWMMMMMMMMM",
	"MMMMMMMMMMMWk,                         .OMMMNx,  'o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;. .lKWMMMMMMM",
	"MMMMMMMMMMXl.                          .OMWk,  ,xXMMMMMMMMMWN0Oxdooodxk0XWMMMMMMMMMNO:. .dXMMMMMM",
	"MMMMMMMMM0;                            .kXl. .dXMMMMMMMWXkl;..   ....  ..,cxKWMMMMMMMNO;  ;0WMMMM",
	"MMMMMMMWO'                             .l;  :0WMMMMMMNOc.  .;ldkO0K00Oxo:'. .;xXWMMMMMMXo. .kWMMM",
	"MMMMMMWk'                               . .lXMMMMMMNk;. .lkXWMMMMMMMMMMMWN0o,  'dXMMMMMMWx. .xWMM",
	"MMMMMWO'                                  lNMMMMMMKc. .dXWMMMMMMMMMMMMMMMMMMNk;  ,OWMMMMMWk. .kWM",
	"MMMMM0,                                  :XMMMMMM0;  cKMMMMMMMMMMMMMMMMMMMMMMMNd. .xWMMMMMWd. ;KM",
	"MMMMXc                                  .OMMMMMMK; .lNMMMMMMMMMMMMMMMMMMMMMMMMMWk. .kWMMMMMX: .dW",
	"MMMWx.                                  cNMMMMMNl  :XMMMMMMMMMMMMWXNMMMMMMMMMMMMWd. ;KMMMMMMx. ;K",
	"MMMK,                                  .xMMMMMM0, .kMMMMMMMMMMMMMO;dWMMMMMMMMMMMMK; .xMMMMMM0' .O",
	"MMWd.                                  .kMMMMMMk. ,KMMMMMMMMMMMMX: .OMMMMMMMMMMMMWl  lWMMMMMX; .k",
	"MMX;                                   .kMMMMMMk. ,KMMMMMMMMMMMWd.  :XMMMMMMMMMMMNl  oWMMMMMX; .x",
	"MMO.                                   .xMMMMMM0' .OMMMMMMMMMMMO'   .dWMMMMMMMMMMK; .xMMMMMM0' .O",
	"MMx.                                    cNMMMMMNl  lNMMMMMMMMMX:     '0MMMMMMMMMWo. ;KMMMMMMx. ;K",
	"MWo                                     .OMMMMMM0, .dWMMMMMMMWo.      cXMMMMMMMNd. 'OMMMMMMX:  oW",
	"MNl                                      :XMMMMMWk' .oNMMMMMMO.       .xWMMMMMKl. 'OWMMMMMWd. ,KM",
	"MNl                                      .oNMMMMMWO,  ;OWMMMK;         ,0MMWKo' .cKWMMMMMWk. .kWM",
	"MWl                                       .lNMMMMMMXo. .;xKXo           cOx:. .;kNMMMMMMWk. .xWMM",
	"MWo                                    .l;  :KWMMMMMWKd,. .'.            .  'lONMMMMMMMNo. .xWMMM",
	"MMd.                                   .kXl. 'xNMMMMMMMN0o,               :ONMMMMMMMMWO;  ;OWMMMM",
	"MMk.                                   .kMNk,  ,xXMMMMMMMNl               lNMMMMMMMWOc. .oXMMMMMM",
	"MM0'                                   .kMMMXd'  'o0WMMMWk.               .kWMMMWXx;. .l0WMMMMMMM",
	"MMX;                                   .kMMMMMXx;. .;oOX0;                 ;KN0xc.  'oKWMMMMMMMMM",
	"MMNl                                   .kMMMMMMMW0o;.  ..                   ''. .'lkNMMMMMMMMMMMM",
	"MMMx.                                  .kMMMMMMMMMMWKxc.                     .:d0NMMMMMMMMMMMMMMM",
	"MMM0'                                  .kMMMMMMMMMMMMM0,  ;olc;,,''',,;:ll,  ;KMMMMMMMMMMMMMMMMMM",
	"MMMNc                                  .kMMMMMMMMMMMMNc  ,KMMMWWWNNNNWWMMMO' .oWMMMMMMMMMMMMMMMMM",
	"MMMMk.                                 .kMMMMMMMMMMMWx. .kWMMMMMMMMMMMMMMMWd. .OMMMMMMMMMMMMMMMMM",
	"MMMMX:                                 .kMMMMMMMMMMM0,  lNMMMMMMMMMMMMMMMMMX:  :XMMMMMMMMMMMMMMMM",
	"MMMMWx.                                .kMMMMMMMMMMNc  ;KMMMMMMMMMMMMMMMMMMMO' .dWMMMMMMMMMMMMMMM",
	"MMMMMX:                                .kMMMMMMMMMWx. .kMMMMMMMMMMMMMMMMMMMMWo. 'OMMMMMMMMMMMMMMM",
	"MMMMMMk.                               .kMMMMMMMMM0'  oNMMMMMMMMMMMMMMMMMMMMMX:  :XMMMMMMMMMMMMMM",
	"MWNWMMNl                               .kMMMMMMMMXc  ;KMMMMMMMMMMMMMMMMMMMMMMMO. .dWMMMMMMMMMMMMM",
	"MXkKMMM0,                              .kMMMMMMMWd. .kMMMMMMMMMMMMMMMMMMMMMMMMNo  '0MMMMMMMMMMMMM",
	"MXldWMMWk.                             .kMMMMMMMO' .oWMMMMMMMMMMMMMMMMMMMMMMMMMK;  cNMMMMMMMMMMMM",
	"MX:,0MMMNo.                            .kMMMMMMX:  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMk. .xWMMMMMMMMMMM",
	"MX;.oWMMMXc                            .kMMMMMWd. .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl  ,0MMMMMMMMMMM",
	"MX; ,0MMMMX:                           .kMMMMMO' .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,  lNMMMMMMMMMM",
	"MX;  oWMMMMK;                          .kMMMMX:  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk. .xWMMMMMMMMM",
	"MX;  ,0MMMMMK:                         .kMMMWo. 'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl  ,KMMMMMMMMM",
	"MX;   oWMMMMMK:                        .kMMMO. .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,  lNMMMMMMMM",
	"MX;   '0MMMMMMXl                       .kMMK;  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx. .kWMMMMMMM",
	"MX;    cNMMMMMMNo.                     .kMWo  '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc  ;KMMMMMMM",
	"MX;    .kWMMMMMMWk'                    .kWk. .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'  oNMMMMMM",
	"MX;     ;KMMMMMMMMK:                   .kK;  cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd. .kMMMMMM",
	"MX;      lNMMMMMMMMNd.                 .dl  ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  ;XMMMMM",
	"MX;      .xWMMMMMMMMW0c.               .;. .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO' .oWMMMM",
	"MX;       '0MMMMMMMMMMNk,                  cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd. .OMMMM",
	"MX;        ;KMMMMMMMMMMMXd.               ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:  :XMMM",
	"MX;         cXMMMMMMMMMMMWKo.            .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO. .dWMM",
	"MX;          lNMMMMMMMMMMMMWKo.          lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo  'OMM",
	"MX;          .lNMMMMMMMMMMMMMWKd'        ';;;;;;::::::::::::::::::::::::::::::::::::::::::,   .l0",
	"MX;           .lNMMMMMMMMMMMMMMMXx;.                                                           .x",
	"MX;             cXMMMMMMMMMMMMMMMMW0l'                                                         .x",
	"MX;              ;0WMMMMMMMMMMMMMMMMMXk:.                                                      .x",
	"MX;               'kWMMMMMMMMMMMMMMMMMMWKx:.                                                   .x",
	"MX;                .oXMMMMMMMMMMMMMMMMMMMMWKxc.                                                .x",
	"MX;                  ;OWMMMMMMMMMMMMMMMMMMMMMWXOo;.                                            .x",
	"MX;                   .lKWMMMMMMMMMMMMMMMMMMMMMMMWKkl,.                                        .x",
	"MX;                     .dXMMMMMMMMMMMMMMMMMMMMMMMMMMWKko:..                                   .x",
	"MX;                       'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl:'.                              .x",
	"MX:                         'dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdl;'.                        .x",
	"MNd,,,,,,,,,,,,,,,,,,,,,,,,,,;dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kdlc;'...              .x",
	"MMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXK0OkxdoolllllllloK",
	"MMMMMMMMMMWWWWWMMMMMMMMMMMMMMWWWWWWWWWWWWMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMWW",
	"MMMMMN0xl:;,,;;:cokXWMMMMMMWk:;;;;;;;;;;;;:lkXWMMMNd;,;;,;;;;;;;;;;;;;oXMWxckNMMMMMMMMMMMMMMMXxl0",
	"MMMWXo.            .cONMMMMWl                .dNMMX;                  '0MNc  ,xXMMMMMMMMMMWXd' .k",
	"MNdcxOo'  ....       .:0WMMWl     .cllcc:.     oNMX;      ............:KMNc    'dXWMMMMMMWx'   .k",
	"Xl   ,d0kx0KXK0Oo'     'OMMWl     .l0WMMNo     ;KMXc      'o0KKXXXXXXXXWMWd.     'oKWMMMMX:    .k",
	"x.    ,KMMMMMMMMMXl     :XMWO;      .;cc;.     oNMWKo'     .,cccccccccdXMWXk:.     .lKWMMX:    .k",
	"l     oWMMMMMMMMMM0'    '0MWKOx;.            'dNMMNxoOd,              '0MNxlkkc.     .c0WX:    .k",
	"o     cXMMMMMMMMMWk.    ,KMNl.ckkc;;;;;;;;:lkXWMMMX; .lOx;.           ,KMNc .:kOl.     .:x;    .k",
	"0,     ;kNWMMMWWNNx.   .oWMNl  .:ONWWWWWWMMMMMMMMMX;   .o00OOOOOOOOOOOKWMNc   .:0Ko.           .k",
	"MO,      ':cc::,':kOl..oNMMNl    .kMMMMMMMMMMMMMMMX;     ;llllllloooooxNMNc    .xMWXd'         .k",
	"MMXd'             .;OKKWMMMNl    .dWMMMMMMMMMMMMMMX;                  '0MNc    .xMMMMXx,       .k",
	"MMMWXkl,..      .':dKWMMMMMWl.   .xWMMMMMMMMMMMMMMX:                  ,0MNl    .xMMMMMMNk;.    .k",
	"MMMMMMMWX0OkkOOOKNWMMMMMMMMWXOkkkOXMMMMMMMMMMMMMMMW0xxxxxxxxxxxxxxxxxxONMWKkkkkOXMMMMMMMMN0kxxxOX",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMNKKKKNMMMMMMMMMMWXKKKXWMNKKKKKKKKKKKKKKKKNMWXKKKKKKKKKKKKKKXNM",
	"MMMMMMMMMNo,xWMMMMMMMMMMMMMMMMMMMMMk'...oWMMMMMMMMMK;...:XMKl..............'kMK:..............'OM",
	"MMMMMMMMXl. .dKNMMMMMMMMMMMMMMMMMMMx.   cNMMMMMMMMMNo.  ,KMKOd'            .xM0'              .xM",
	"MMMMMMMM0,   .'oNMMMMMMMMMMMMMMMMMMx.   cNMMMMMMMMMN0k:.;KWd'lkdccccccccccco0M0'    .,ccccccccoKM",
	"MMMMMMKoxk'     lXMMMMMMMMMMMMMMMMMx.   cNMMMMMMMMM0;;xxkXWo  .oO00000XWMMMMMMNl.    ,x0KKKKKKKNM",
	"MMMMM0; .dk,     :KMMMMMMMMMMMMMMMMx.   cNMMMMMMMMM0' .:OWWo     .....;0MMMMMMN0x;     .......'OM",
	"MMMWO,   .k0;     ;KMMMMMMX0OOOO0XWx.   cNMMMMMMMMM0'   ;XWo          '0MMMMMMK:;xd,          .kM",
	"MMWk'    lXMK:.    ,0MMMMWO:,,,;;xWx.   cNMMMMMMMMM0'   ,KWo    'cccccdXMMMMMM0, .ckdcccccccccoKM",
	"MWx.   .oNMMMXOc    'OWMMMWNNNNNNWMx.   ;KWNK000KNM0'   ,KWo    oWMMMMMMMMMMMM0'   ,x000000000KNM",
	"Nd.   .dNMMMMMMXl.   .kWMMMMMMMMMMMx.    .oOx,...kM0'   ,KWo    oWMMMMMMMMMMMM0,     .........'kM",
	"o.   .xWMMMMMMMMNo.   .xWMMMMMMMMMMx.      'dkc..xM0'   ,KWo    oWMMMMMMMMMMMM0,              .xM",
	"dllllOWMMMMMMMMMMNklcclxXMMMMMMMMMMKolllllllo0N0xKMXxlllxNW0ollo0MMMMMMMMMMMMMNxcccccccccclcccoKM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
	};
	
	const char L_logo[195][153] 	= 
	{
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko;..oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl;.     oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d;.         oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl'.            oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc.                oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc.                   oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l'                      oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx;.                        oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l.                           oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0OkxddoooooddxkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc.                             oWMMMMMMMMMMMMMMMMMMMMMMNKOdl:,...               ..';cox0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMNk:.                               oWMMMMMMMMMMMMMMMMMWXOdc'.         .....'''.....         .;lx0NMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMNO;.                                 lWMMMMMMMMMMMMMMW0d:.      .';codkOKKXXNNNNNXXK0Oxdl:,.      .,lkXWMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMW0:.                                   lWMMMMMMMMMMMW0o,.     .:okKNWMMMMMMMMMMMMMMMMMMMMMMMWXOxl,.     .cxXWMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMKl.                                     lWMMMMMMMMMXx;.    .;oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkl'.    .lOWMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMNx'                                       lWMMMMMMWKo'    .:xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl'    .:kNMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMW0:.                                        lWMMMMWKo.    'o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:.    ;kNMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMNx.                                          lWMMMNx'    ,xXMMMMMMMMMMMMMMMMMMWNXK0OkkkkO00XNWMMMMMMMMMMMMMMMMMMW0l.   .:0WMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMXc.                                           lWMW0;    'xNMMMMMMMMMMMMMMMWXOdl;'..        ...,:lx0NWMMMMMMMMMMMMMMWKl.   .oXMMMMMMMMMMMM",
	"MMMMMMMMMMMMMW0;                                             lWNd.   .oXMMMMMMMMMMMMMMXkl;.         ....         .':d0NMMMMMMMMMMMMMWO;    ;0WMMMMMMMMMM",
	"MMMMMMMMMMMMWk'                                              lKl.   ,OWMMMMMMMMMMMMNOl'     ..;coxkO0KK00Okdoc,.     .;dKWMMMMMMMMMMMMXo.   'kWMMMMMMMMM",
	"MMMMMMMMMMMWk.                                               ;;   .cXMMMMMMMMMMMMXx,.    'cx0NWMMMMMMMMMMMMMMMWXOo;.    .cOWMMMMMMMMMMMWk'   .dWMMMMMMMM",
	"MMMMMMMMMMWx.                                                    .oNMMMMMMMMMMMNx,    .ckXMMMMMMMMMMMMMMMMMMMMMMMMWKd;.   .c0WMMMMMMMMMMW0;   .dWMMMMMMM",
	"MMMMMMMMMWk.                                                    .oNMMMMMMMMMMW0:    .oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO:.   .oNMMMMMMMMMMM0;   .kWMMMMMM",
	"MMMMMMMMWO'                                                     lNMMMMMMMMMMWx.   .lKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;    :KMMMMMMMMMMM0'   '0MMMMMM",
	"MMMMMMMM0,                                                     ;KMMMMMMMMMMNd.   ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.   ,0MMMMMMMMMMWx.   cXMMMMM",
	"MMMMMMMXc                                                     .kMMMMMMMMMMWd.   ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.   ;KMMMMMMMMMMNl   .xWMMMM",
	"MMMMMMWd.                                                     cNMMMMMMMMMMO'   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.   cXMMMMMMMMMMO'   :XMMMM",
	"MMMMMM0'                                                     .kMMMMMMMMMMX:   .kMMMMMMMMMMMMMMMMMMMMMXKNMMMMMMMMMMMMMMMMMMMMNl   .xWMMMMMMMMMNc   .OMMMM",
	"MMMMMNl                                                      ,KMMMMMMMMMMk.   cNMMMMMMMMMMMMMMMMMMMMNo,kMMMMMMMMMMMMMMMMMMMMM0'   :XMMMMMMMMMMx.  .dWMMM",
	"MMMMMO.                                                      cNMMMMMMMMMWo   .kMMMMMMMMMMMMMMMMMMMMWk. ;XMMMMMMMMMMMMMMMMMMMMNc   '0MMMMMMMMMMO.   lNMMM",
	"MMMMNl                                                       lWMMMMMMMMMNc   '0MMMMMMMMMMMMMMMMMMMMK;  .oWMMMMMMMMMMMMMMMMMMMWo   .kMMMMMMMMMM0'   :NMMM",
	"MMMM0'                                                       lWMMMMMMMMMN:   '0MMMMMMMMMMMMMMMMMMMNl    .OMMMMMMMMMMMMMMMMMMMWd   .kMMMMMMMMMMK,   :XMMM",
	"MMMWx.                                                       cNMMMMMMMMMNl   .OMMMMMMMMMMMMMMMMMMWk.     :XMMMMMMMMMMMMMMMMMMNl   .OMMMMMMMMMM0'   cNMMM",
	"MMMNc                                                        :XMMMMMMMMMWd.  .dWMMMMMMMMMMMMMMMMMK,      .dWMMMMMMMMMMMMMMMMMK,   ;KMMMMMMMMMMk.   oWMMM",
	"MMMK,                                                        '0MMMMMMMMMM0'   :XMMMMMMMMMMMMMMMMNl        'OMMMMMMMMMMMMMMMMWd.  .oWMMMMMMMMMWo   .xMMMM",
	"MMMO.                                                        .dWMMMMMMMMMNl   .dWMMMMMMMMMMMMMMWx.         :XMMMMMMMMMMMMMMWk.   ;KMMMMMMMMMMK;   ,KMMMM",
	"MMMk.                                                         ,KMMMMMMMMMMK;   .kWMMMMMMMMMMMMM0,          .dWMMMMMMMMMMMMWO'   'OMMMMMMMMMMWx.   oWMMMM",
	"MMMd.                                                          oNMMMMMMMMMMO'   'kWMMMMMMMMMMMNc            '0MMMMMMMMMMMNd.   'kWMMMMMMMMMMK,   ,0MMMMM",
	"MMWd                                                           .kWMMMMMMMMMWO'   .dNMMMMMMMMMWx.             cXMMMMMMMMW0:.   ,OWMMMMMMMMMMNc   .dWMMMMM",
	"MMWd                                                            'OMMMMMMMMMMW0;    ;OWMMMMMMM0'              .xWMMMMMW0l.   .lKMMMMMMMMMMMNo.   cNMMMMMM",
	"MMMd                                                             ,0MMMMMMMMMMMXo.   .:kNMMMMXc                ,0MMWXkc.    ;OWMMMMMMMMMMMNd.   :KMMMMMMM",
	"MMMx.                                                        ..   'OWMMMMMMMMMMW0c.    'oOXNd.                 c0kc'    .;kNMMMMMMMMMMMMXo.   ;KMMMMMMMM",
	"MMMk.                                                        cx.   .dNMMMMMMMMMMMW0l.     ',.                   .     'lOWMMMMMMMMMMMMMK:    :KMMMMMMMMM",
	"MMMO.                                                        lNO,   .cKWMMMMMMMMMMMWXxc'                          .,lkXWMMMMMMMMMMMMMNk'   .lXMMMMMMMMMM",
	"MMM0'                                                        lWMXl.   .dXMMMMMMMMMMMMMWXOl.                      ,ONMMMMMMMMMMMMMMMW0:.   'kWMMMMMMMMMMM",
	"MMMK;                                                        lWMMWk,    ,xXMMMMMMMMMMMMMWO.                      .kWMMMMMMMMMMMMMW0l.   .lKWMMMMMMMMMMMM",
	"MMMN:                                                        lWMMMMXd.    'dKWMMMMMMMMMMK;                        ;KMMMMMMMMMMMNOc.   .:OWMMMMMMMMMMMMMM",
	"MMMWo                                                        lWMMMMMWKo'    .ckNMMMMMMMWo.                         lNMMMMMMMWKd;.   .;kNMMMMMMMMMMMMMMMM",
	"MMMMx.                                                       lWMMMMMMMWXd,     'lkXWMMMk.                          .kMMMMWKd:.    .cONMMMMMMMMMMMMMMMMMM",
	"MMMM0'                                                       lWMMMMMMMMMMNOc.     .:oOO;                            ;0Kxl,.    .,dKWMMMMMMMMMMMMMMMMMMMM",
	"MMMMX;                                                       lWMMMMMMMMMMMMMXkc'      .                              ..     .;o0NMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMWo                                                       lWMMMMMMMMMMMMMMMWNOd:'.                                   .,cxKWMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMk.                                                      lWMMMMMMMMMMMMMMMMMMMWXd.                                .oKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMK;                                                      lWMMMMMMMMMMMMMMMMMMMMNl    ;xxdlc:;,''.....'',;:codd'   .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMWo                                                      lWMMMMMMMMMMMMMMMMMMMWx.   'OMMMMMMWWNNNXXNNNWWWMMMMWk.   'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMO.                                                     lWMMMMMMMMMMMMMMMMMMM0,   .dWMMMMMMMMMMMMMMMMMMMMMMMMNl    :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMX:                                                     lWMMMMMMMMMMMMMMMMMMNc    :XMMMMMMMMMMMMMMMMMMMMMMMMMMK,   .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMWx.                                                    lWMMMMMMMMMMMMMMMMMWx.   'OMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.   'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMK;                                                    lWMMMMMMMMMMMMMMMMM0,   .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc    cXMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMWd.                                                   lWMMMMMMMMMMMMMMMMXc    cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,   .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMX;                                                   lWMMMMMMMMMMMMMMMWd.   '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.   '0MMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMWx.                                                  lWMMMMMMMMMMMMMMM0'   .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc    cNMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMX:                                                  lWMMMMMMMMMMMMMMXc    cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'   .xWMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMWMMMMMMO.                                                 lNMMMMMMMMMMMMMWd.   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.   ,0MMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMNKXMMMMMWo.                                                lNMMMMMMMMMMMMMO'   .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:    lNMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMXdkWMMMMMK;                                                lNMMMMMMMMMMMMX:    lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'   .xWMMMMMMMMMMMMMMMMMMMMMMM",
	"MMNc:KMMMMMMO'                                               lNMMMMMMMMMMMWd.   ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.   ,KMMMMMMMMMMMMMMMMMMMMMMM",
	"MMN:.xWMMMMMWd.                                              cNMMMMMMMMMMMO.   .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:    lNMMMMMMMMMMMMMMMMMMMMMM",
	"MMN: ;XMMMMMMNl                                              cNMMMMMMMMMMK;    lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.   .kMMMMMMMMMMMMMMMMMMMMMM",
	"MMNc .xWMMMMMMK:                                             cNMMMMMMMMMNo    ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.   ;KMMMMMMMMMMMMMMMMMMMMM",
	"MMNc  ;KMMMMMMM0,                                            cNMMMMMMMMWk.   .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;    oNMMMMMMMMMMMMMMMMMMMM",
	"MMNc  .xWMMMMMMWO'                                           cNMMMMMMMMK;    oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.   .kMMMMMMMMMMMMMMMMMMMM",
	"MMN:   ;KMMMMMMMWk.                                          cNMMMMMMMNl    ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo    ;KMMMMMMMMMMMMMMMMMMM",
	"MMNc   .xWMMMMMMMWk.                                         cNMMMMMMWk.   .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;   .oWMMMMMMMMMMMMMMMMMM",
	"MMNc    ;KMMMMMMMMWk.                                        cNMMMMMMK;   .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.   .OMMMMMMMMMMMMMMMMMM",
	"MMNc    .dWMMMMMMMMWk.                                       cNMMMMMNl    :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl    :XMMMMMMMMMMMMMMMMM",
	"MMNc     ;KMMMMMMMMMWO'                                      cNMMMMWx.   'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,   .dWMMMMMMMMMMMMMMMM",
	"MMN:     .dWMMMMMMMMMW0;                                     cNMMMM0,   .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.   'OMMMMMMMMMMMMMMMM",
	"MMNc      ,0MMMMMMMMMMMK:                                    cNMMMNc    :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl    cXMMMMMMMMMMMMMMM",
	"MMNc       lNMMMMMMMMMMMXl.                                  cNMMWx.   'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,   .dWMMMMMMMMMMMMMM",
	"MMNc       .kMMMMMMMMMMMMNx.                                 cNMM0,   .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.   '0MMMMMMMMMMMMMM",
	"MMNc        ;KMMMMMMMMMMMMW0;                                cNMXc    cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc    cNMMMMMMMMMMMMM",
	"MMNc         oNMMMMMMMMMMMMMXl.                              cNWd.   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'   .xWMMMMMMMMMMMM",
	"MMN:         .kMMMMMMMMMMMMMMWk,                             cN0'   .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.   ,0MMMMMMMMMMMM",
	"MMN:          ;KMMMMMMMMMMMMMMMXl.                           cKc    cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc    cNMMMMMMMMMMM",
	"MMN:           lNMMMMMMMMMMMMMMMWO,                          :l.   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'   .xWMMMMMMMMMM",
	"MMN:           .xWMMMMMMMMMMMMMMMMXd.                        ..   .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.   ,KMMMMMMMMMM",
	"MMN:            'OWMMMMMMMMMMMMMMMMWKc.                           lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:    lNMMMMMMMMM",
	"MMN:             ,0MMMMMMMMMMMMMMMMMMWO:.                        ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'   .kWMMMMMMMM",
	"MMN:              :XMMMMMMMMMMMMMMMMMMMNk,                      .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.   ;KMMMMMMMM",
	"MMN:               cXMMMMMMMMMMMMMMMMMMMMNx,                    lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:    lNMMMMMMM",
	"MMN:               .lNMMMMMMMMMMMMMMMMMMMMMNx,                 ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.   .kMMMMMMM",
	"MMN:                .oNMMMMMMMMMMMMMMMMMMMMMMNk;.             .l0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXKKXXXXX0c    ;OXNWMMM",
	"MMN:                 .oNMMMMMMMMMMMMMMMMMMMMMMMNOc.             ............................................................................     ..cXMMM",
	"MMN:                  .oNMMMMMMMMMMMMMMMMMMMMMMMMW0o'                                                                                              ;XMMM",
	"MMN:                   .lXMMMMMMMMMMMMMMMMMMMMMMMMMMXx;.                                                                                           ;XMMM",
	"MMN:                     cXMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l'                                                                                         ;XMMM",
	"MMN:                      ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc.                                                                                      ;XMMM",
	"MMN:                       'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:.                                                                                   ;XMMM",
	"MMN:                        .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;.                                                                                ;XMMM",
	"MMN:                          :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:.                                                                             ;XMMM",
	"MMN:                           'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl'.                                                                         ;XMMM",
	"MMN:                            .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:.                                                                      ;XMMM",
	"MMN:                              .dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo;.                                                                  ;XMMM",
	"MMN:                                ,kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo:.                                                              ;XMMM",
	"MMN:                                 .:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdc,.                                                         ;XMMM",
	"MMN:                                   .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkoc'.                                                    ;XMMM",
	"MMN:                                     .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOdc;..                                              ;XMMM",
	"MMN:                                       .cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0koc;'.                                        ;XMMM",
	"MMN:                                         .:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxoc;'..                                ;XMMM",
	"MMWOollllllllllllllllllllllllllllllllllllllllloxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxolc;,'..                      ;XMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0Okxdollcccc::ccccccccxNMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMWWNXXXXXNNWMMMMMMMMMMMMMMMMMMWNNNNNNNNNNNNNNNNNNNNWMMMMMMMMMMMMWNXNNNXXNNNNNNNNNNNNNNNNXNNXXXNWMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXMMMM",
	"MMMMMMMMMMWXOdc;,'......';cokKWMMMMMMMMMMMMNd'''''''''''''''''''',:okKWMMMMMMMXc............................;OMMMWx,:kNMMMMMMMMMMMMMMMMMMMMMMMMMXd,cMMMM",
	"MMMMMMMMXx:.                 .;o0WMMMMMMMMMNc                        .cOWMMMMMK,                            .xMMMWo   ;xXMMMMMMMMMMMMMMMMMMMMWKo'  ;MMMM",
	"MMMMMWWWXl.                     .:OWMMMMMMMNc                          .oNMMMMK,                            .xMMMWo     ,dXWMMMMMMMMMMMMMMMW0l.    ;MMMM",
	"MMMMXl,lKNKl.                     .cKMMMMMMNc        'cccccccc:.        .oWMMMK,                            .xMMMWo       'oKWMMMMMMMMMMMMXl.      ;MMMM",
	"MMM0;   .c0NKo,,coxkkxdoc,.         ,OWMMMMNc        ,xNMMMMMMWXc        ,KMMMK,         .cxkkkkkkkkkkkkkkkkOXMMMWo         .lKWMMMMMMMMMMk.       ;MMMM",
	"MMK;      .c0WNWMMMMMMMMMN0l.        '0MMMMNc          ,xXMMMMWXc        ,KMMMXl.         .cOWMMMMMMMMMMMMMMMMMMMW0;          .c0WMMMMMMMMk.       ;MMMM",
	"MWo        'OMMMMMMMMMMMMMMWO,        cNMMMWk,           ':ccc;.         oNMMMMNO:.         .;ccccccccccccccoKMMMMMNk;.         .cONMMMMMMk.       ;MMMM",
	"MK,       .xWMMMMMMMMMMMMMMMMk.       '0MMMMWXx;.                      .lXMMMMN0KNOc.                       .xMMMWOkXNO:.         .;kNMMMMk.       ;MMMM",
	"M0'       .OMMMMMMMMMMMMMMMMM0'       .OMMMNkxXNk:.                  .:OWMMMMMK;.l0N0l.                     .xMMMWo.'oKN0c.          ;xNMMk.       ;MMMM",
	"MK;       .dWMMMMMMMMMMMMMMMWk.       '0MMMNc 'oKNOc'............';cxKWMMMMMMMK;  .cONKo'                   .xMMMWo   .l0NKl.          ,dXk.       ;MMMM",
	"MWo.       .dNMMMMMMMMMMMMMM0,        lNMMMN:   .l0NNXXXXXXXXXXXXNWMMMMMMMMMMMK,    .:kNXxc::::::ccccccccccclKMMMWo     .c0NKo'          ',        ;MMMM",
	"MMX:         ;xKWMMMMMMMWXXWXo'      ,0MMMMNc     .c0WMMMMMMMMMMMMMMMMMMMMMMMMK,       :KMMMMMMMMMMMMMMMMMMMMMMMMWo       .xWWXd'                  ;MMMM",
	"MMMK:          .;coddoll;..cONXd,   ;0MMMMMN:       .kMMMMMMMMMMMMMMMMMMMMMMMMK,       .cxxxxxxxxkkkkkkkkkkkOXMMMWo        lWMMMXx,                ;MMMM",
	"MMMMNd.                     .:kNXx:oXMMMMMMNc       .xMMMMMMMMMMMMMMMMMMMMMMMMK,                            .xMMMWo        lWMMMMMNk;.             ;MMMM",
	"MMMMMWKo'                     .:0WWMMMMMMMMNc       .xMMMMMMMMMMMMMMMMMMMMMMMMK,                            .xMMMWo        lWMMMMMMMNO:.           ;MMMM",
	"MMMMMMMWXkc'.                .:xXMMMMMMMMMMNc       .xMMMMMMMMMMMMMMMMMMMMMMMMK,                            .xMMMWo        lWMMMMMMMMMW0c.         ;MMMM",
	"MMMMMMMMMMWN0xoc;,''''',;clx0NWMMMMMMMMMMMMNd,'''''':OMMMMMMMMMMMMMMMMMMMMMMMMXl............................,OMMMWx,....'',xWMMMMMMMMMMMW0l'.......lMMMM",
	"MMMMMMMMMMMMMMMMWWNNNNWWWMMMMMMMMMMMMMMMMMMMWWWWWWWNWWMMMMMMMMMMMMMMMMMMMMMMMMMNXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMWNNNNNNNNWMMMMMMMMMMMMMMWNXXXXXXXNMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNWMMMMMMMMMMMMMMMMMWNNNNNNWMMMWNNNNNNNNNNNNNNNNNNNNNNNNNWMMMWNNNNNNNNNNNNNNNNNNNNNNNNWMMMMM",
	"MMMMMMMMMMMMMMMMWO:lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.....lXMMMMMMMMMMMMMMMNo'....'oNMMXo'......................,kMMMk,'''''''''''''''''''''';OWMMMM",
	"MMMMMMMMMMMMMMMWk'  :KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl      ,KMMMMMMMMMMMMMMMN:      :NMMWKl.                      dWMWd.                      .dWMMMM",
	"MMMMMMMMMMMMMMWk.    ;xKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl      ,KMMMMMMMMMMMMMMMWO,     :NMMX0X0c.                    dWMWd.                      .dWMMMM",
	"MMMMMMMMMMMMMMO'       ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl      ,KMMMMMMMMMMMMMMMMWXx'   :NMMO,;kXO:.                 .dWMWd                       .xWMMMM",
	"MMMMMMMMMMMMWWXl.       'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMWl      ,KMMMMMMMMMMMMMMMNxdKKo. :NMMO. .:0XOkOO000000000000000NMMWd.       'dOOOOOOOOOOOOO0NMMMMM",
	"MMMMMMMMMMMNoc0No.       'kWMMMMMMMMMMMMMMMMMMMMMMMMMMWl      ,KMMMMMMMMMMMMMMMX: 'xXKldNMMO.   .l0NWWWWWWWWWMMMMMMMMMMMM0;        .dXWWWWWWWWWWWWMMMMMM",
	"MMMMMMMMMMXc  ,ONd.       .xWMMMMMMMMMMMMMMMMMMMMMMMMMWl      ,KMMMMMMMMMMMMMMMX:   ,kXWMMMO.     .,,,,,,,,,:OMMMMMMMMMMMMXd'        .,,,,,,,,,,,:OMMMMM",
	"MMMMMMMMMK:    'kNx.       .dNMMMMMMMMMMMMMMMMMMMMMMMMWl      ,KMMMMMMMMMMMMMMMN:     :0WMMO.               .dMMMMMMMMMMM0xKKo.                  .xWMMMM",
	"MMMMMMMMK;      'OWk.       .oNMMMMMMMMMMWNNNNNNNNNNWMWl      ,KMMMMMMMMMMMMMMMX:      cNMMO.               .dMMMMMMMMMMWd.'dX0c.                .dWMMMM",
	"MMMMMMM0,       cXMWO'       .lXMMMMMMMMWx'''''''''l0MWl      ,KMMMMMMMMMMMMMMMX:      :NMMO.               .xMMMMMMMMMMWd.  ,kXO:.              .xWMMMM",
	"MMMMMWO'       lXMMMW0o,       cXMMMMMMMWk'''''''''lKMWl      ,KMMMMMMMMMMMMMMMN:      :NMMO.      ckkOkkkkOOXMMMMMMMMMMMd.    ;OX0kkkkkkkkkkkkkkOXMMMMM",
	"MMMMWk.      .oNMMMMMMW0;       :KMMMMMMMMMWWWWMMWWMMMWl      ,KMMMWWWWWWWWWMMMN:      :NMMO.     .xMMMMMMMMMMMMMMMMMMMMMd.     '0WWWWWWWWWWWWWWWMMMMMMM",
	"MMMWx.      .dNMMMMMMMMMK:       ;0WMMMMMMMMMMMMMMMMMMWl       ,dXWXd:;;;;;lKMMN:      :NMMO.     .xMMMMMMMMMMMMMMMMMMMMMd.      ';;;;;;;;;;;;;;;cOMMMMM",
	"MMNd.      .xWMMMMMMMMMMMXc       ,OWMMMMMMMMMMMMMMMMMWl         'xXKl.    .OMMN:      :NMMO.     .xMMMMMMMMMMMMMMMMMMMMMd.                      .dWMMMM",
	"MNl.      .kWMMMMMMMMMMMMMXl.      'kWMMMMMMMMMMMMMMMMWl           ,kX0c.  .OMMX:      :NMMO.     .xMMMMMMMMMMMMMMMMMMMMMd.                      .dWMMMM",
	"Xl.      'OWMMMMMMMMMMMMMMMNo.      .kWMMMMMMMMMMMMMMMWo            .:0NO:.'OMMXc      cNMMO'     .xMMMMMMMMMMMMMMMMMMMMMd.                      .dWMMMM",
	"XOxxxxxxkKWMMMMMMMMMMMMMMMMMN0xxxxxxx0WMMMMMMMMMMMMMMMWKkxxxxxxxxxxxxx0WMN0ONMMW0kxxxxx0WMMNOxxxxxOXMMMMMMMMMMMMMMMMMMMMMXkxxxxxxxxxxxxxxxxxxxxxxkXMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
	};	
	
	const char XL_logo[205][188] 	= 
	{
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo::OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko;.   .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko;.       .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:.           .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,.              .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxc.                  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx:.                     .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc.                        .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl'                           .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd;.                             .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl.                                .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk;.                                  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kxolc:;;,,'''',,;;:clodxOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd,                                     .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0koc;'.                          ..,:lxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd'                                       .xMMMMMMMMMMMMMMMMMMMMMMMMWKko:'.               ........                .,cd0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo'                                         .xMMMMMMMMMMMMMMMMMMMMWXkl,.         ..';cloxkOO00KKKKK00Okxdoc:,..         .':d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'                                           .xMMMMMMMMMMMMMMMMMWKx:.        .,:ox0XNWMMMMMMMMMMMMMMMMMMMMMMWWNKOdl;.        .,oONMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMNx,                                             .xMMMMMMMMMMMMMMWXx:.       .;okKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0dc'.      .,o0WMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMWO:.                                              .xMMMMMMMMMMMMW0l'      .,lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:.      .;xXWMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMXo.                                                .xMMMMMMMMMMNk:.     .,oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:.      'oKWMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMWk,                                                  .xMMMMMMMMNk;.     .cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd,.     .oKWMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMXl.                                                   .xMMMMMMWO;.     'dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO:.     .dXMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMWO,                                                     .xMMMMWKl.     ,xXMMMMMMMMMMMMMMMMMMMMMMMWNKOkdollccccllodxO0XNWMMMMMMMMMMMMMMMMMMMMMMW0c.     ,kNMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMNd.                                                      .xMMMNx'     'dXMMMMMMMMMMMMMMMMMMMMWKkoc,..                ..';lx0XWMMMMMMMMMMMMMMMMMMMWO:.    .cKMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMXl.                                                       .xMMKc.    .lKMMMMMMMMMMMMMMMMMMWXkl,.                            ..:d0NMMMMMMMMMMMMMMMMMMNx'     'kWMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMM0;                                                         .xW0,     ,kWMMMMMMMMMMMMMMMMWXx:.        ..,:clodxxxxxdolc;'.        .,o0NMMMMMMMMMMMMMMMMMKl.    .dNMMMMMMMMMMM",
	"MMMMMMMMMMMMMWO,                                                          .dk'     cKMMMMMMMMMMMMMMMMWOc.       .;ox0XWWMMMMMMMMMMMMMWNKOdc,.      .;xXWMMMMMMMMMMMMMMMNx.    .lXMMMMMMMMMM",
	"MMMMMMMMMMMMWO'                                                           .,.    .oNMMMMMMMMMMMMMMMNk:.     .,lOXWMMMMMMMMMMMMMMMMMMMMMMMMMN0d:.      'oKMMMMMMMMMMMMMMMW0,     cXMMMMMMMMM",
	"MMMMMMMMMMMWO'                                                                  .xWMMMMMMMMMMMMMMWO:.     .lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx;.     'dXMMMMMMMMMMMMMMMK;     cXMMMMMMMM",
	"MMMMMMMMMMWO'                                                                  .xWMMMMMMMMMMMMMMXo.     'dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc.     ;OWMMMMMMMMMMMMMMK:     lNMMMMMMM",
	"MMMMMMMMMM0,                                                                  .dWMMMMMMMMMMMMMW0;     .dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;     .dNMMMMMMMMMMMMMM0;    .dWMMMMMM",
	"MMMMMMMMMK:                                                                   lNMMMMMMMMMMMMMWk'     :0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.    .cXMMMMMMMMMMMMMMO'    'OMMMMMM",
	"MMMMMMMMNl                                                                   ;KMMMMMMMMMMMMMWx.    .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0;     cXMMMMMMMMMMMMMWd.    :XMMMMM",
	"MMMMMMMWx.                                                                  .kWMMMMMMMMMMMMWk.    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:     cNMMMMMMMMMMMMMX:    .xWMMMM",
	"MMMMMMMO'                                                                   cXMMMMMMMMMMMMM0,    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;    .dWMMMMMMMMMMMMMk.    :XMMMM",
	"MMMMMMXc                                                                   .xWMMMMMMMMMMMMNl     lNMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMO'    '0MMMMMMMMMMMMMX;    .OMMMM",
	"MMMMMWx.                                                                   ,KMMMMMMMMMMMMMO.    ,KMMMMMMMMMMMMMMMMMMMMMMMMMMWxlKMMMMMMMMMMMMMMMMMMMMMMMMMMWo.    lNMMMMMMMMMMMMWo.    oWMMM",
	"MMMMMK;                                                                    cNMMMMMMMMMMMMWo    .oWMMMMMMMMMMMMMMMMMMMMMMMMMM0' lNMMMMMMMMMMMMMMMMMMMMMMMMMM0'    ,KMMMMMMMMMMMMMO.    :NMMM",
	"MMMMWx.                                                                    dWMMMMMMMMMMMMX:    .OMMMMMMMMMMMMMMMMMMMMMMMMMMX:  .kWMMMMMMMMMMMMMMMMMMMMMMMMMNc    .kMMMMMMMMMMMMM0,    ,KMMM",
	"MMMMX:                                                                    .xMMMMMMMMMMMMMK,    ,KMMMMMMMMMMMMMMMMMMMMMMMMMWd.   ;KMMMMMMMMMMMMMMMMMMMMMMMMMWo    .dWMMMMMMMMMMMMX;    '0MMM",
	"MMMMk.                                                                    .xMMMMMMMMMMMMM0'    ;XMMMMMMMMMMMMMMMMMMMMMMMMMO'     oNMMMMMMMMMMMMMMMMMMMMMMMMWd.    oWMMMMMMMMMMMMX;    '0MMM",
	"MMMNl                                                                     .xMMMMMMMMMMMMMK,    ,KMMMMMMMMMMMMMMMMMMMMMMMMX:      .kWMMMMMMMMMMMMMMMMMMMMMMMWo    .dWMMMMMMMMMMMMX;    '0MMM",
	"MMMK,                                                                      dWMMMMMMMMMMMMX;    'OMMMMMMMMMMMMMMMMMMMMMMMWd.       ;KMMMMMMMMMMMMMMMMMMMMMMMNc    .kMMMMMMMMMMMMM0,    ,KMMM",
	"MMMk.                                                                      lNMMMMMMMMMMMMNl    .dWMMMMMMMMMMMMMMMMMMMMMMO.        .oWMMMMMMMMMMMMMMMMMMMMMM0'    ,KMMMMMMMMMMMMMO.    :XMMM",
	"MMWo                                                                       ;KMMMMMMMMMMMMMk.    :XMMMMMMMMMMMMMMMMMMMMMX:          .OMMMMMMMMMMMMMMMMMMMMMNl     oWMMMMMMMMMMMMWd.    oWMMM",
	"MMNc                                                                       .kMMMMMMMMMMMMMX:    .dWMMMMMMMMMMMMMMMMMMMNo.           :XMMMMMMMMMMMMMMMMMMMWx.    ,KMMMMMMMMMMMMMX:    .OMMMM",
	"MMX;                                                                        cNMMMMMMMMMMMMMO.    'OMMMMMMMMMMMMMMMMMMMk.            .dWMMMMMMMMMMMMMMMMMWO'    .kWMMMMMMMMMMMMMk.    :XMMMM",
	"MM0'                                                                        .kWMMMMMMMMMMMMNo.    ;0MMMMMMMMMMMMMMMMMK;              'OMMMMMMMMMMMMMMMMWk'    .dNMMMMMMMMMMMMMX:    .xWMMMM",
	"MMO.                                                                         ;KMMMMMMMMMMMMMNl     ,0WMMMMMMMMMMMMMMNo                :XMMMMMMMMMMMMMMNd.    .dNMMMMMMMMMMMMMWd.    :XMMMMM",
	"MMO.                                                                          oNMMMMMMMMMMMMMXl.    'xNMMMMMMMMMMMMWk.                .dWMMMMMMMMMMMWO:     .xWMMMMMMMMMMMMMMO'    .OMMMMMM",
	"MMO.                                                                          .xWMMMMMMMMMMMMMNo.    .cKWMMMMMMMMMMK;                  '0MMMMMMMMMW0l.     ;0WMMMMMMMMMMMMMMK;    .dWMMMMMM",
	"MMO.                                                                           .kWMMMMMMMMMMMMMWk,     .oKWMMMMMMMNl                    cXMMMMMMNOc.     .dXMMMMMMMMMMMMMMMK:     cXMMMMMMM",
	"MMO.                                                                            .xWMMMMMMMMMMMMMMKl.     .lONMMMMWx.                    .xWMMWKd;.     .lKWMMMMMMMMMMMMMMMK:     :XMMMMMMMM",
	"MM0'                                                                       '.    .dNMMMMMMMMMMMMMMW0c.     .,oONW0,                      'kOo;.      .l0WMMMMMMMMMMMMMMMM0;     :KMMMMMMMMM",
	"MMK,                                                                      .dx.    .lXMMMMMMMMMMMMMMMW0l.       ':,                        .       .;dXWMMMMMMMMMMMMMMMMWk'     cXMMMMMMMMMM",
	"MMX;                                                                      .xWO,     ,OWMMMMMMMMMMMMMMMWXx:.                                    .;o0NMMMMMMMMMMMMMMMMMMXl.    .oXMMMMMMMMMMM",
	"MMN:                                                                      .xMMKc     .lXMMMMMMMMMMMMMMMMMWKxc'.                             .cxKWMMMMMMMMMMMMMMMMMMMNk,     'kWMMMMMMMMMMMM",
	"MMWl                                                                      .xMMMNd.     'xNMMMMMMMMMMMMMMMMMMWNk'                            cNMMMMMMMMMMMMMMMMMMMMW0c.    .cKWMMMMMMMMMMMMM",
	"MMWd.                                                                     .xMMMMWKc.     ,xNMMMMMMMMMMMMMMMMMWd.                            .kWMMMMMMMMMMMMMMMMMW0l.     'xNMMMMMMMMMMMMMMM",
	"MMMk.                                                                     .xMMMMMMNk;      ,dXWMMMMMMMMMMMMMM0'                              ;KMMMMMMMMMMMMMMMNOc.     .oXMMMMMMMMMMMMMMMMM",
	"MMM0'                                                                     .xMMMMMMMMNx,      .l0NMMMMMMMMMMMX:                                lNMMMMMMMMMMMWXx;.     .lKWMMMMMMMMMMMMMMMMMM",
	"MMMK;                                                                     .xMMMMMMMMMMNk;.     .,d0WMMMMMMMWd.                                .kWMMMMMMMWXkc.      .oKWMMMMMMMMMMMMMMMMMMMM",
	"MMMNc                                                                     .xMMMMMMMMMMMMNOc.      .,oOXWMMMO'                                  ;KMMMMNKxc.      .;xXWMMMMMMMMMMMMMMMMMMMMMM",
	"MMMWd.                                                                    .xMMMMMMMMMMMMMMWKd;.       .:dOO:                                   .oX0xl,.       'lONMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMO.                                                                    .xMMMMMMMMMMMMMMMMMWKd;.        .                                     ...       .'lONMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMK;                                                                    .xMMMMMMMMMMMMMMMMMMMMWKxc,.                                                 .:oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMNl                                                                    .xMMMMMMMMMMMMMMMMMMMMMMMMN0xl'                                          ':oOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMk.                                                                   .xMMMMMMMMMMMMMMMMMMMMMMMMMMMNo      ..                          ..     .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMK,                                                                   .xMMMMMMMMMMMMMMMMMMMMMMMMMMMk.    .lKKOxdoc:;;,'''...'',,;:cloxk0k,     :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMNl                                                                   .xMMMMMMMMMMMMMMMMMMMMMMMMMMK;     ;KMMMMMMMMWWWNNNNNNNNWWWMMMMMMMWk.    .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMk.                                                                  .xMMMMMMMMMMMMMMMMMMMMMMMMMNo     .OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMX:                                                                  .xMMMMMMMMMMMMMMMMMMMMMMMMWk.    .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,     cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMWd.                                                                 .xMMMMMMMMMMMMMMMMMMMMMMMMK;     :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.    .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMK,                                                                 .xMMMMMMMMMMMMMMMMMMMMMMMNl     'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc     ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMWo                                                                 .xMMMMMMMMMMMMMMMMMMMMMMWk.    .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,     cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMM0,                                                                .xMMMMMMMMMMMMMMMMMMMMMM0,     :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMWo                                                                .xMMMMMMMMMMMMMMMMMMMMMNl     '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc     ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMM0,                                                               .xMMMMMMMMMMMMMMMMMMMMWx.    .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'     lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMWd.                                                              .xMMMMMMMMMMMMMMMMMMMM0,     cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMK;                                                              .xMMMMMMMMMMMMMMMMMMMNc     ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMWk.                                                             .xMMMMMMMMMMMMMMMMMMWd.    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'     lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MWNWMMMMMMMNl                                                             .dMMMMMMMMMMMMMMMMMM0'     cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.    .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MWkOWMMMMMMM0,                                                            .dMMMMMMMMMMMMMMMMMXc     ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:     ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MWdcKMMMMMMMWx.                                                           .dMMMMMMMMMMMMMMMMWd.    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.     oNMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MWo.xWMMMMMMMNl                                                           .dMMMMMMMMMMMMMMMMO'     lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.    .kMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MWo.;XMMMMMMMMK;                                                          .dMMMMMMMMMMMMMMMX:     ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;     ;XMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MWo .xWMMMMMMMWO'                                                         .dMMMMMMMMMMMMMMWo.    .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.    .oWMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MWo  ;XMMMMMMMMWx.                                                        .dMMMMMMMMMMMMMMO.     lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo     .OMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MWo  .xWMMMMMMMMNo.                                                       .dMMMMMMMMMMMMMK:     ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;     :XMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MWo   ;KMMMMMMMMMXc                                                       .dMMMMMMMMMMMMNo.    .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.    .dWMMMMMMMMMMMMMMMMMMMMMMMM",
	"MWo   .xWMMMMMMMMMK:                                                      .dMMMMMMMMMMMMk.     oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     'OMMMMMMMMMMMMMMMMMMMMMMMM",
	"MWo    ;KMMMMMMMMMM0;                                                     .dMMMMMMMMMMMK;     ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,     cXMMMMMMMMMMMMMMMMMMMMMMM",
	"MWo    .xWMMMMMMMMMM0,                                                    .dMMMMMMMMMMNo     .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.    .dWMMMMMMMMMMMMMMMMMMMMMM",
	"MWo     ;KMMMMMMMMMMWO,                                                   .dMMMMMMMMMWk.    .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     '0MMMMMMMMMMMMMMMMMMMMMM",
	"MWo     .xWMMMMMMMMMMWO,                                                  .dMMMMMMMMMK;     :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,     cXMMMMMMMMMMMMMMMMMMMMM",
	"MWo      ;KMMMMMMMMMMMW0,                                                 .dMMMMMMMMNl     'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.    .xWMMMMMMMMMMMMMMMMMMMM",
	"MWo      .xWMMMMMMMMMMMW0;                                                .dMMMMMMMWx.    .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc     ,0MMMMMMMMMMMMMMMMMMMM",
	"MWo       ;KMMMMMMMMMMMMMK:                                               .dMMMMMMM0,     :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'     lNMMMMMMMMMMMMMMMMMMM",
	"MWo       .dWMMMMMMMMMMMMMXc                                              .dMMMMMMNl     'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.    .xWMMMMMMMMMMMMMMMMMM",
	"MWo        '0MMMMMMMMMMMMMMNo.                                            .dMMMMMWx.    .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc     ,KMMMMMMMMMMMMMMMMMM",
	"MWo         cNMMMMMMMMMMMMMMNx.                                           .dMMMMM0,     cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'     lNMMMMMMMMMMMMMMMMM",
	"MWo         .kWMMMMMMMMMMMMMMWO,                                          .dMMMMXc     ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.    .kWMMMMMMMMMMMMMMMM",
	"MWo          ;KMMMMMMMMMMMMMMMWKc                                         .dMMMWd.    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:     ;KMMMMMMMMMMMMMMMM",
	"MWo          .oWMMMMMMMMMMMMMMMMNd.                                       .dMMM0'     cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'     oNMMMMMMMMMMMMMMM",
	"MWo           .OMMMMMMMMMMMMMMMMMWO,                                      .dMMXc     ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo.    .kWMMMMMMMMMMMMMM",
	"MWo            :XMMMMMMMMMMMMMMMMMMXl.                                     dMWd.    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;     ;KMMMMMMMMMMMMMM",
	"MWo            .oNMMMMMMMMMMMMMMMMMMWk,                                    dWO'     lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.    .oNMMMMMMMMMMMMM",
	"MWo             .kWMMMMMMMMMMMMMMMMMMMXl.                                 .dX:     ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo     .OMMMMMMMMMMMMM",
	"MWo              ,KMMMMMMMMMMMMMMMMMMMMWO;                                .oo.    .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;     :XMMMMMMMMMMMM",
	"MWo               cXMMMMMMMMMMMMMMMMMMMMMXd.                               ,.     lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.    .dWMMMMMMMMMMM",
	"MWo               .dWMMMMMMMMMMMMMMMMMMMMMW0c.                                   ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     'OMMMMMMMMMMM",
	"MWo                .kWMMMMMMMMMMMMMMMMMMMMMMWO;                                 .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;     :XMMMMMMMMMM",
	"MWo                 'OMMMMMMMMMMMMMMMMMMMMMMMMNx,                              .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.    .dWMMMMMMMMM",
	"MWo                  ;KMMMMMMMMMMMMMMMMMMMMMMMMMNx'                            ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl     '0MMMMMMMMM",
	"MWo                   :XMMMMMMMMMMMMMMMMMMMMMMMMMMXd'                         .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,     cXMMMMMMMM",
	"MWo                    cXMMMMMMMMMMMMMMMMMMMMMMMMMMWXd'                      .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx.    .xWMMMMMMM",
	"MWo                     lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd,                    :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc     ,0MMMMMMM",
	"MWo                     .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx;                  :xxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOkkkkOOOOOOOOOl.     :kO0NMMM",
	"MWo                      .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:.                                                                                                                        'OMMM",
	"MWo                       .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l.                                                                                                                      .OMMM",
	"MWo                        .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd,.                                                                                                                   .OMMM",
	"MWo                          cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc.                                                                                                                 .OMMM",
	"MWo                           ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;.                                                                                                              .OMMM",
	"MWo                            ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o,                                                                                                            .OMMM",
	"MWo                             .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl'                                                                                                         .OMMM",
	"MWo                              .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc.                                                                                                      .OMMM",
	"MWo                                ;0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl'                                                                                                   .OMMM",
	"MWo                                 .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOl,.                                                                                               .OMMM",
	"MWo                                  .:KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:.                                                                                            .OMMM",
	"MWo                                    'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,.                                                                                        .OMMM",
	"MWo                                      :0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xc'.                                                                                    .OMMM",
	"MWo                                       .lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0dc'.                                                                                .OMMM",
	"MWo                                         'xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xc,.                                                                            .OMMM",
	"MWo                                           ;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKko:'.                                                                       .OMMM",
	"MWo                                            .;ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xl;..                                                                  .OMMM",
	"MWo                                              .;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0xl;'.                                                             .OMMM",
	"MWo                                                .;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdc;..                                                       .OMMM",
	"MWo                                                  .;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkdl:'..                                                .OMMM",
	"MWo                                                    .;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kdl:,..                                         .OMMM",
	"MWOc:::::::::::::::::::::::::::::::::::::::::::::::::::::lOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kdoc:,'..                               .OMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKOkxdolc:;,'....................,0MMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXKKKKK000KKKKKKKKKXWMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNXXKKKKK000KKKKKKKKKXWMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMWNK0OkxxxxkkO0KNWMMMMMMMMMMMMMMMMMMMMX0OOOOOOOOOOOOOOOOOOOOOOOOO0KNWMMMMMMMMMMMMMN0kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMMMMWKk0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxM",
	"MMMMMMMMMMMMWXOdc;..           ..,cdOXWMMMMMMMMMMMMMMWo.                         ...;lkXWMMMMMMMMMM                                     .dWMMMNc .:ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd, M",
	"MMMMMMMMMWKx:.                       .:xKWMMMMMMMMMMMNl                                .cOWMMMMMMMM                                      oWMMMNc   .;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'   M",
	"MMMMMMMMMNd.                            .cONMMMMMMMMMWl                                  .cKMMMMMMM                                      oWMMMNc      ,xXMMMMMMMMMMMMMMMMMMMMMMMMW0l.     M",
	"MMMMMW0ONMWOc.                            .:OWMMMMMMMWl                                    ,0MMMMMM                                      oWMMMNc        'dKMMMMMMMMMMMMMMMMMMMMW0c.       M",
	"MMMMXl. ,xXMW0c.                            .oXMMMMMMNl          .:dddddddddddl;.           :XMMMMM                                     .dWMMMNc          .oKWMMMMMMMMMMMMMMMMNo.         M",
	"MMM0;     ,dXMWKl..'coxkkOkxdoc'.             :KMMMMMNl           ,xNMMMMMMMMMMNd.          .OMMMMM            .cxkkkkkkkkkkkkkkkkkkkkkkOXMMMMNc            .l0WMMMMMMMMMMMMMMK,          M",
	"MMK,        'oKWWXKNMMMMMMMMMMMN0o'            ;KMMMMWl             ,xXMMMMMMMMMO'          .kMMMMM             .cOWMMMMMMMMMMMMMMMMMMMMMMMMMMWd.             .cOWMMMMMMMMMMMMK,          M",
	"MXc           :XMMMMMMMMMMMMMMMMMMXo.           lNMMMWo.              'd0XXXXK0d,           ,0MMMMMc.             .:kXXXXXXXXXXXXXXXXXXXXWMMMMMWOc.             .:ONMMMMMMMMMMK,          M",
	"Mk.          .kWMMMMMMMMMMMMMMMMMMMWx.          .OMMMMXd,               .......            .dWMMMMMW0l.              ...................'xMMMMMMMW0l.             .;kNMMMMMMMMK,          M",
	"Ml           oWMMMMMMMMMMMMMMMMMMMMMNl           oWMMMMMXx;                               .dNMMMMMM0WWKl.                                oWMMMNkdXWWKo.              ,xXMMMMMMK,          M",
	"Mc          .kMMMMMMMMMMMMMMMMMMMMMMMk.          cNMMW0ONMNk:.                          .c0WMMMMMMM.c0WWKd'                              oWMMMX: 'oKWWKd'              'dXWMMMK,          M",
	"Ml          .xWMMMMMMMMMMMMMMMMMMMMMWd.          lWMMNl.,xXMWOc.                     .,o0WMMMMMMMMM  .cONMXx,                            oWMMMX:   .l0WMXd,              .oKWMK,          M",
	"Md.          ;KMMMMMMMMMMMMMMMMMMMMMK;          .xMMMNl   'dXMW0l::::::;;;;;;;:::cldkKWMMMMMMMMMMMM    .:kNMNk;.                         oWMMMX:     .cOWMNx;              .l00,          M",
	"MK;           ;0WMMMMMMMMMMMMMMMMMMX:           ;KMMMNl     'oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM       ;xNMNOlclcccccccllllllllllllllo0MMMMX:       .:ONMNk:.             .,.          M",
	"MWk.           .l0WMMMMMMMMMMMMMMMMNx,         .kWMMMNl       .l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM         ,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:         .cXMMNO:.                        M",
	"MMWx.            .;ok0XNNNNXK0ko:l0WMXx,      .xWMMMMNl         .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          ;XMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMX:          .OMMMMW0c.                      M",
	"MMMWk'               ..''''...    .cONMNk;.  'kWMMMMMNl          .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM          .,;;;;;;;;;;;;:::::::::::::cOWMMMX:          .OMMMMMMW0l.                    M",
	"MMMMMKl.                            .:kNMNOloKMMMMMMMNl          .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                      oWMMMX:          .OMMMMMMMMWKo'                  M",
	"MMMMMMW0c.                             ;kNMMMMMMMMMMMNl          .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                      oWMMMX:          .OMMMMMMMMMMMXd,                M",
	"MMMMMMMMWKd;.                         .;xNMMMMMMMMMMMNl          .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                      oWMMMN:          .OMMMMMMMMMMMMMXx;              M",
	"MMMMMMMMMMMWKxc,.                 .,cx0WMMMMMMMMMMMMMNl          .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                      oWMMMX:          .OMMMMMMMMMMMMMMMNk;.           M",
	"MMMMMMMMMMMMMMMNKOxolc:;;;;::cloxOXNMMMMMMMMMMMMMMMMMWkc:::::::::lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;kWMMMNx;;;;;;;,,,lKMMMMMMMMMMMMMMMMMNOc,,,,,,,,,,M",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMNo;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl''''''''dNMMMMMMMMMMMMMMMMMMMMWk,''''''':0MMMM0:'''''''''''''''''''''''''''''''cKMMMO;''''''''''''''''''''''''''''''lXM",
	"MMMMMMMMMMMMMMMMMMMMXc  .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        :NMMMMMMMMMMMMMMMMMMMMWo        .kMMMMNk;                              .OMMWd                               '0M",
	"MMMMMMMMMMMMMMMMMMMK:    .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        :NMMMMMMMMMMMMMMMMMMMMWd.       .kMMMMMMNx'                            .OMMWd                               '0M",
	"MMMMMMMMMMMMMMMMMMK;      .l0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        :NMMMMMMMMMMMMMMMMMMMMMNx'      .kMMMM0xKWXd.                          .OMMWd                               '0M",
	"MMMMMMMMMMMMMMMMMK;         .cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        :NMMMMMMMMMMMMMMMMMMMMMMMXd.    .kMMMMx.'dXWKl.                        .OMMWd                               '0M",
	"MMMMMMMMMMMMMMMMMNo.          :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        :NMMMMMMMMMMMMMMMMMMMMWOkNWKl.  .kMMMMx.  ,kNW0lcooooooooooooooooooooookXMMMd          .:oooooooooooooooooookNM",
	"MMMMMMMMMMMMMMW00WNo.          ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        :NMMMMMMMMMMMMMMMMMMMMWo.,kNW0c..kMMMMx.    :OWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMd.          'dXMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMWx..xWNx.          ,0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        :NMMMMMMMMMMMMMMMMMMMMWo  .:OWWOo0MMMMx.     .c0XNNNNNNNNNNNNWMMMMMMMMMMMMMMXo.           ,xXNNNNNNNNNNNNNNNWMM",
	"MMMMMMMMMMMMNd.  .dWWk.          'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        :NMMMMMMMMMMMMMMMMMMMMWo    .c0WWWMMMMx.       ..'..........,xWMMMMMMMMMMMMMMW0c.           .'''''''''''''''lXM",
	"MMMMMMMMMMMNo.    .oNWk'          .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        :NMMMMMMMMMMMMMMMMMMMMWo      .lKWMMMMx.                     lWMMMMMMMMMMMMMK0NWO:.                         ,KM",
	"MMMMMMMMMMXl.      .lNWO,          .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'        :NMMMMMMMMMMMMMMMMMMMMWo        ,0MMMMx.                     lWMMMMMMMMMMMMMx.:OWNk;                        ,KM",
	"MMMMMMMMMK:         .kMM0;          .dNMMMMMMMMMMMXKKKKKKKKKKKKMMM0'        :NMMMMMMMMMMMMMMMMMMMMWo        .kMMMMx.                     lWMMMMMMMMMMMMMd. .c0WNx'                      ,KM",
	"MMMMMMMMK;         .oNMMMK:          .oNMMMMMMMMMM'............MMM0'        :NMMMMMMMMMMMMMMMMMMMMWo        .kMMMMx.                     oWMMMMMMMMMMMMMd.   .lKWXd.                    ,KM",
	"MMMMMMW0,         .dNMMMMMKc.         .lXMMMMMMMWM'............MMM0'        :NMMMMMMMMMMMMMMMMMMMMWo        .kMMMMx.        ;dddddddddddxKWMMMMMMMMMMMMMd.     .dXWKxoooooooooodddddddddONM",
	"MMMMMWO'         .xWMMMMMMMX0l          cXMMMMMMMMXKKKKKKKKKKXXMMM0'        :NMMMMMMMMMMMMMMMMMMMMWo        .kMMMMx.       .dWMMMMMMMMMMMMMMMMMMMMMMMMMMd.       ;0MMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMWk.         .kWMMMMMMMMMMNo.         :KMMMMMMMMMMMMMMMMMMMMMMM0'        ;0WMMMWXXXXXXXXXXNWMMMWo        .kMMMMx.       .dWMMMMMMMMMMMMMMMMMMMMMMMMMMd.       .oXXXXXXXXXXXXXXXXNNNNXNWM",
	"MMMWx.         'OWMMMMMMMMMMMMNd.         ;0MMMMMMMMMMMMMMMMMMMMMM0'         .:kWMNx,........:KMMMWo        .kMMMMx.       .dWMMMMMMMMMMMMMMMMMMMMMMMMMMd.        ......................cKM",
	"MMNd.         ,0WMMMMMMMMMMMMMMWx.         ,OWMMMMMMMMMMMMMMMMMMMM0'           .:0WWO;       '0MMMWo        .kMMMMx.       .dWMMMMMMMMMMMMMMMMMMMMMMMMMMd.                              '0M",
	"MNo.         ;KMMMMMMMMMMMMMMMMMWk.         'kWMMMMMMMMMMMMMMMMMMM0'             .lKWNx,     '0MMMWo        .kMMMMx.       .dWMMMMMMMMMMMMMMMMMMMMMMMMMMd.                              '0M",
	"Ml          :KMMMMMMMMMMMMMMMMMMMWO'         .xWMMMMMMMMMMMMMMMMMM0'               .oXWXd'   '0MMMWo        .kMMMMx.       .dWMMMMMMMMMMMMMMMMMMMMMMMMMMd.                              '0M",
	"M.        .lXMMMMMMMMMMMMMMMMMMMMMWO,         .xMMMMMMMMMMMMMMMMMM0,                 ,xNWKo. '0MMMWo        .kMMMMx.       .xWMMMMMMMMMMMMMMMMMMMMMMMMMMx.                              ,0M",
	"MxxxxxxxxxONMMMMMMMMMMMMMMMMMMMMMMMMKxdddddddddOMMMMMMMMMMMMMMMMMMNOxxxxxxxxxxxxxxxxxxOXMMWKkONMMMWKxxxxxxxxkXMMMMXkxxxxxxxkXMMMMMMMMMMMMMMMMMMMMMMMMMMMXxddddddddddddddddddddddddddddddOMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"
	};


	// 谢谢您 https://www.ascii-art-generator.org/
	switch (size)
	{
		//Smallest
		case 0:
		
			for (unsigned int x = 0; x < 76; x++)
			{
				printf("%s\n", S_logo[x] );
			}
			break;

		//Medium
		case 1:
		
			for (unsigned int x = 0; x < 102; x++)
			{
				printf("%s\n", M_logo[x] );
			}
			break;

		//Bigger
		case 2:
			
			for (unsigned int x = 0; x < 195; x++)
			{
				printf("%s\n", L_logo[x] );
			}
			break;

		//Biggest
		case 3:
			
			for (unsigned int x = 0; x < 205; x++)
			{
				printf("%s\n", XL_logo[x] );
			}
			break;

		default:
			printf("\t     Hello\n\t    Welcome\n\tto Open A-Life!\n");
			printf("\n\tIncorrect logo size used :(");
			printf("\n\tHope this is ok and gets the job done :D\n\n");
			break;
	}
}














































































































































































